spring:
  application:
    name: pay-tm-bck

  datasource:
    url: jdbc:postgresql://localhost:5432/paytm_basic_db
    username: nitinbhalla
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

